### ISSUE TITLE
Bug in account for DeploymentLib.Ps1

### ISSUE THREAD

**Issue by ElliottMiller** [Azure/azure-iot-remote-monitoring#128]
the function GetAzureAccountInfo on line 535 is expecting that $account.Id (from Get-AzureAccount) is a string, when it is in fact an array. When you try to use it as a string, it automatically casts the array to a string which works just fine when you only have access to one subscription, but fails when you have access to multiple subs.

The fix is something like this:

$accountId = $account.Id

	if($account.Id -is [system.array]) {
		$accountId = $account.Id[0]
	}

And then just use $accountId instead of $account.Id in the code below.

**Comment by jamesweb-ms** [comment]
This issue is related to having either multiple subscriptions or multiple accounts.  We have a fix for this issue in [Az_national_cloud branch](https://github.com/Azure/azure-iot-remote-monitoring/tree/az_national_cloud).  We are planning to merge this branch later today after some more testing.  If you want to give it a try and give use feedback, that would be great!

**Comment by aguilaaj** [comment]
Fixed in #151
