### ISSUE TITLE
Iot suit EventProcessor web job is always in "Pending Restart" status.

### ISSUE THREAD

**Issue by saviganesh** [Azure/azure-iot-remote-monitoring#132]
We  have created a custom device and trying to Send Command to this device , but Command status is unable to change from "Peding" to "Success".
We have deployed the azure-iot-remote-monitoring solution , using "Cloud deploy" option. For deployment we followed the commands as given [here](https://github.com/Azure/azure-iot-remote-monitoring/wiki/Cloud-deployment) .
After deploying , everything is working fine except the Eventprocessor Web Job.
Eventprocessor webjob stastus is always in "Pending Restart" state. 
Please see below screenshot.

![image](https://cloud.githubusercontent.com/assets/18184670/14168445/19467fac-f740-11e5-8e1d-6c33aa335ac0.png)

Any help would be greatly apreciated.

**Comment by jamesweb-ms** [comment]
This usually happens when you deploy without having the correct Azure SDK installed.  We require 2.7.1 currently (looking at removing this dependency in future).  If you don't have that version installed (side by side with other versions work), then build/deployment works fine, but the role will fail to start because it can't find the right version of the diagnostics library.

To verify or figure out what is really happening, you can use the webapp's log streaming:

1) go to portal.azure.com
2) go to resource group with same name as your deployment
3) click the ... at top of summary to see all resources
4) click the App service that ends in -jobhost
5) click Diagnostic logs
6) Turn Application Logging (Filesystem) on and set level to verbose then click save
7) click tools at top of Web app page
8) click Log stream

You should now be able to see output from your webjob including any exceptions being throw.

**Comment by aguilaaj** [comment]
Hi @saviganesh - can you validate if you've resolved the issue?

**Comment by aguilaaj** [comment]
@saviganesh - closing for now, reopen if necessary.
