### ISSUE TITLE
Development Environment Setup

### ISSUE THREAD

**Issue by ScottLiuGitHub** [Azure/azure-iot-remote-monitoring#147]
Hello, 

I have a few questions: 

1. I am getting the following Subscription ID error message although the build.cmd can pull the correct Subscription ID from my profile. Is it because I am using free trial? 

Set-AzureRmContext : Cannot validate argument on parameter 'SubscriptionId'.
The argument is null or empty. Supply an argument that is not null or empty
and then try the command again.
At C:\development\azureiot\Common\Deployment\DeploymentLib.ps1:823 char:48
+     Select-AzureRmSubscription -SubscriptionId $global:SubscriptionId
+                                                ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureRmContext], Parameter
   BindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure
   .Commands.Profile.SetAzureRMContextCommand

2. I am also getting the following error when creating resources 

Unable to create unique name for resource localrm for url blob.core.windows.net
At C:\development\azureiot\Common\Deployment\DeploymentLib.ps1:293 char:13
+             throw ("Unable to create unique name for resource {0} for url
{1}" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : OperationStopped: (Unable to creat...ore.windows
   .net:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to create unique name for resource localr
   m for url blob.core.windows.net


Thanks

**Comment by jtanner-msft** [comment]
Hi Scott - I saw you had also asked some questions in this other issue that James has answered:
https://github.com/Azure/azure-iot-remote-monitoring/issues/148 
Since this issue was numerically raised first, did he also help you to answer these questions with his response to 148?
Or are you still having the above problems based upon the suggestions he made?

**Comment by jamesweb-ms** [comment]
Actually I think this issue is related to having either multiple subscriptions or multiple accounts.  We have a fix for this issue in [Az_national_cloud branch](https://github.com/Azure/azure-iot-remote-monitoring/tree/az_national_cloud).  We are planning to merge this branch later today after some more testing.  If you want to give it a try and give use feedback, that would be great!

**Comment by ScottLiuGitHub** [comment]
Thanks!

I used the Az_national_cloud branch. Now my first error is gone. My second error is still there: 

Unable to create unique name for resource localrm for url blob.core.windows.net
At C:\development\azurelocal\azure-iot-remote-monitoring\Common\Deployment\Depl
oymentLib.ps1:293 char:13
+             throw ("Unable to create unique name for resource {0} for url
{1}" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : OperationStopped: (Unable to creat...ore.windows
   .net:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to create unique name for resource localr
   m for url blob.core.windows.net

**Comment by jamesweb-ms** [comment]
Closing this and tracking DNS issue in #148
