### ISSUE TITLE
Code duplication? RemoteMonitoring.json and RemoteMonitoringMapKey.json

### ISSUE THREAD

**Issue by ckarras** [Azure/azure-iot-remote-monitoring#159]
The files RemoteMonitoring.json and RemoteMonitoringMapKey.json contain mostly identical code, except for Bing Maps. Are both files really used?

**Comment by jamesweb-ms** [comment]
Templates are pretty inflexible.  We needed to support deploying with out maps for the German datacenter.  As a side benefit, this template also allows you to share the map key across several solutions.  This is especially useful for those doing demo's since bing map limits two keys per subscription.

**Comment by aguilaaj** [comment]
Closing if there are no further questions. Feel free to re-open or create a new issue for additional questions if need be. Thanks!
