### ISSUE TITLE
Unable to login to webpage with localdeploy

### ISSUE THREAD

**Issue by kazuhei777** [Azure/azure-iot-remote-monitoring#192]
Hi guys,
I face very similar issue such as https://github.com/Azure/azure-iot-remote-monitoring/issues/161
Local deploy successes without trouble, and device simulator and webjob simulator are working correctly.  
However, same as the link, after I login using my account, the website redirecting to login page every single time.
Unfortunately, I could not solve this issue with the solution with the link. My account does not have any limit now.(I'm using azure with MSDN subscription professional edition)

Anybody getting the same issue I have?

**Comment by manashty** [comment]
Hi Kazuhei777,

Have you tried clearing your browser cache/trying another browser?
If that doesn't fix the problem, maybe we should try adding some proper error messages in case of such redirections.

Thanks.

**Comment by kazuheihayashi** [comment]
Hi Manashty,
I tried clearing browser cache and using oher browsrers, but still faced same issue.
Do you have any idea how to get detail of this issues detail?

**Comment by kazuhei777** [comment]
Hi Manashty,
 I tried clearing browser cache and using oher browsrers, but still faced same issue.
 Do you have any idea how to get detail of this issues ?

**Comment by manashty** [comment]
Good. Thanks.


As I am new to the code, I couldn't find the sign in controller in at a first glance. We should find that part and try to see if we can prompt the user accordingly.


This might also be some Azure active directory problem. But at least you should be able to login as guest I guess.


That's what I could think of for now.


Experts could help us in here better.






On Tue, Jul 5, 2016 at 4:33 AM -0300, "kazuheihayashi" <notifications@github.com> wrote:





Hi Manashty,
I tried clearing browser cache and using oher browsrers, but still faced same issue.
Do you have any idea how to get detail of this issues detail?



---

**Comment by jamesweb-ms** [comment]
The most likely reason you are seeing this is the app you are using has a different reply URL than your current dev box.  If multiple folks are using the same app, then you need to make sure you are all using the same port.

The other option if you can't match ReplyURLs (because of port conflicts), is to create a Test AAD for yourself (often this is recommended instead of using corp AAD) and set your local deployment to that AAD.

Please read through this document to see if helps you narrow down your issue and resolve it.  If not, feel free to reply here and I can get you some more detailed help.
https://azure.microsoft.com/en-us/documentation/articles/iot-suite-permissions/

**Comment by jtanner-msft** [comment]
kazuhei777,

  Once you’ve had a chance to review James’s suggestions above, please let us know if those worked for you or if you still require assistance.  Thanks.

**Comment by kazuhei777** [comment]
Hi all,
I really appreciate you guys help. 
However.....
I don't know why, but it working correctly without any redirecting now.
(I din't change any thing.)
So, I'gonna close this post.
