### ISSUE TITLE
Issue at Local deployment and debugging

### ISSUE THREAD

**Issue by SudhakarJonnakuti** [Azure/azure-iot-remote-monitoring#291]
Error:

At G:\Azure-IoT\2.Customize a preconfigured solution\Trail_1\azure-iot-remote-monitoring\Common\Deployment\DeploymentLib.ps1:704 char:23
+ $result = Invoke-RestMethod -Method "GET" -Uri $uri -Headers @{"Auth ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ArgumentException
+ FullyQualifiedErrorId: System.ArgumentException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Steps followed

1. clone the repository
2. opened developer Command Prompt for VS2015 as an Administrator
3. navigated to repository root directory
4. when i run build.cmd local got this error

Am using Azure powershell : 1.6.0 Version

**Comment by jtanner-msft** [comment]
Hi @SudhakarJonnakuti,

  I wanted to let you know that I’ve tried to repro the issue you encountered.  First I tried with Azure Powershell 1.5.0 installed, and once I verified that still was working I upgraded to 1.6.0.  Rebooted my system and then tried the deployment again with a fresh clone of the repository.  Everything appeared to work the same so for me things appear to be working correctly.

  The one thing I did in each deployment that I did want to mention was that I chose to deploy to an AAD Tenant where I was the global admin.  If you do not currently have such an AAD Tenant, then I would suggest that you create one and target that for your IoT Suite deployment, instead of an AAD Tenant where you are just a user.  (If you are not offered the choice of which AAD Tenant to deploy into, then you currently only have one available and it is being chosen by default.)

  If you need instructions on how to create a new AAD Tenant please let me know.  Currently those services are managed in the classic portal: 
https://manage.windowsazure.com/microsoft.onmicrosoft.com?hashseg=Workspaces/All/dashboard  

Thanks,

**Comment by SudhakarJonnakuti** [comment]
Hi @jtanner-msft 

I am having Free Trial subscription account and am the global admin, still getting the same error.

**Comment by jtanner-msft** [comment]
What version of Windows Powershell are you running?  In addition to the newer Azure PowerShell, you should be running 4.x of Windows PowerShell or later.
To check the version you can use this in a PowerShell environment:
 $psversiontable.psversion

**Comment by SudhakarJonnakuti** [comment]
Thank you @jtanner-msft 
Solved, earlier i am having Windows Powershell 3.X.
Now i installed the Windows Powershell 4.0 and follow the steps it’s working.
