### ISSUE TITLE
VSO continuous integration

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#398]
I was wondering if the team had any hints/tips towards using VSO for CI of this project?!

I have gone some way into getting it working but I am stumbling because of the need to provide user input when running the PS script: PrepareIoTSample.ps1 even when having deployed the solution manually first.

the tasks I currently undertake are:
Nuget Restore
Build Solution
Test Assembilies
Inline PS:

```
param
(
    [Parameter(Mandatory=$true, HelpMessage="The directory the file should be created")]
    [string] $dir
)

$filePath = [String]::Format("{0}\surfacenet-staging.config.user", $dir)

$content = @"
<Environment version="1.0">
  <!-- General Settings -->
  <setting name="AllocationRegion" value="North Europe" />
```

...

```
</Environment>
"@

$content -replace '\n', "`r`n" | out-file $filePath
```

Azure Powershell Script: Common/Deployment/PrepareIoTSample.ps1
    args: mydeploymentname $(BuildConfiguration)
    Connection type: Azure Classic (which injects the authentication details).

I really don't like that I am having to create the user.config file (as this leaves private information on the build server unless I also run a manual task to clean it up) but it also doesn't seem to run successfully anyway..

Any advice (which would also benefit from being added to the wiki) would be most appreciated.

Thanks.

**Comment by networkfusion** [comment]
I should also state that I have to use an on premises build agent as the hosted one only has azure powershell 1.3.4. Annoying (anyone able to push the VSO team to update it) but simple for me personally to work around.

**Comment by networkfusion** [comment]
One last thing, if you need justification for making this sample CI compatible, here are my reasons:
If you want this sample to be the basis of a real-world solution
1. Anyone serious about transforming their business will want to automate their build processes
2. it makes your life easier for testing multiple scenarios
3. It advertises VSO
and I am sure there are many other examples.

**Comment by rraomsft** [comment]
Thanks for the note @networkfusion  - we'll keep this one open as an enhancement for now. 
Feel free to post this enhancements on our [Azure IoT UserVoice](https://feedback.azure.com/forums/321918-azure-iot)

**Comment by networkfusion** [comment]
Just to add my latest findings:

in Common/Deployment/DeploymentLib.ps1 line 860 if you wrap

`ValidateLoginCredentials`
with
```
    if ([Environment]::UserInteractive) 
    {
        ValidateLoginCredentials
    }
```
and in Common/Deployment/PrepareIoTSample.ps1 line 264 wrap
`start $global:site`
with
```
if ([Environment]::UserInteractive) 
        {
            start $global:site
        }
```
it is possible to inject credentials using an azure resource manager SPN. Along with my inline PS in the first comment and build tasks for the solution and webprojects (for packaging) it is possible to deploy using TFS!

**Comment by Skielex** [comment]
Thanks for sharing this. 

I'm currently investigating how to use TFS/TSO and CI with this project. There are a bunch of resources (eg. [this](https://azure.microsoft.com/en-us/documentation/articles/vs-azure-tools-resource-groups-ci-in-vsts/)) on how to use TSO and CI with ARM out there, but most of them use were simple templates compared to this project.

Another thing I need to work out is how to provision and maintain a SQL database as a part of the setup. The provisioning is pretty straight forward with modifications to the ARM template and PS script. As for setting up and maintaining the DB schema I hope [this ](https://blogs.msdn.microsoft.com/ssdt/2016/04/06/sqldb-cicd-intro/#) post will help me out.

Since this project seems like very good starting point for an actual product, I agree with @networkfusion that some guidance on how best to use TFS/TSO and CI would be very helpful.

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
