### ISSUE TITLE
Unable to create unique name for resource localrm when 

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-iot-remote-monitoring#430]
While i am trying to run the solution locally by execuing build.cmd local i am getting the following error:

Unable to create unique name for resource localrm forurl blob.core.windows.net

Below is a screen shot of the error message:
![image](https://user-images.githubusercontent.com/11993393/26942710-137439c2-4c51-11e7-9dea-d4aa2f3e74e7.png)

How would i fix this issue?

Thanks.

**Comment by zhang-hua** [comment]
@melzoghbi , this script will check the name availability for storage account. So it seems that 'localrm' account has been used by other Azure user which prevented you to deploy remote monitoring solution. You can append some random number or dates to the solution name to avoid name conflict (e.g. localrm0609). This is the quickest way to resolve the name issue.

**Comment by melzoghbi** [comment]
I pulled this branch but i am facing the a different issue on next line no. 294 instead of 293.

![image](https://user-images.githubusercontent.com/11993393/27040906-658c3f7c-4f60-11e7-9316-462eadcbf9c4.png)

Looking forward to your insights.

**Comment by melzoghbi** [comment]
Any update on this issue?

**Comment by zhang-hua** [comment]
@melzoghbi , can you try to run the command in Powershell and let me know the output:
```
$name = "{0}{1:x5}" -f "LocalRM", (get-random -max 1048575)
$hubname = $name + ".azure-devices.net"
Write-Host $hubname
[Net.Dns]::GetHostEntry($hubname)
```

**Comment by melzoghbi** [comment]
Sure, here is the output of this command:

![image](https://user-images.githubusercontent.com/11993393/27296410-ba85ca8c-54ee-11e7-814e-b8422828c0fe.png)

**Comment by zhang-hua** [comment]
@melzoghbi , thanks for your feedback. It seems that the DNS resolution is not quite right because that address doesn't exists in my test from here. I suspect your local DNS resolution always return you an incorrect response which should be handled by this PR. would you please help to run this commands so that I can fix it for you?
```
[Net.Dns]::GetHostEntry("ramdomsites97f51.nonexistentdomainname.com")
Invoke-WebRequest -Uri "https://LocalRM4a9a6.azure-devices.net/devices"
Invoke-WebRequest -Uri "https://LocalRM.azure-devices.net/devices"
```

**Comment by melzoghbi** [comment]
Thanks @zhang-hua for taking care of this and helping me to fix it. Here is an error i am getting when trying to execute above commands in PS:

![image](https://user-images.githubusercontent.com/11993393/27349517-85e707aa-55c5-11e7-8e69-17e7c9dfe30c.png)

**Comment by zhang-hua** [comment]
@melzoghbi , thanks for your feedback. I have pushed another new branch [fix_issue_430](https://github.com/Azure/azure-iot-remote-monitoring/tree/fix_issue_430) for you. please apply this code and see if it works.

Basically I found the DNS problem has little difference from what I can see here. The `localRM4a9a6.azure-devices.net` is an unknown host for me but known at your side. That's why my patch doesn't work. I add some code to distinguish the errors so that we can get a correct name for resource. Hope this can work for you this time.

**Comment by zhang-hua** [comment]
@melzoghbi , how is it going for this issue and patch?

**Comment by melzoghbi** [comment]
@zhang-hua I tried to get latest from the master branch today and while trying to run the solution locally, i am getting the following error:

![image](https://user-images.githubusercontent.com/11993393/28186900-c0777102-67ea-11e7-92cd-b897e8d005b4.png)

Any thoughts on how to resolve this issue since it has been awhile and i see other issues reported the same problem such as: #432.

Thanks.

**Comment by ankitscribbles** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
