### ISSUE TITLE
Build.cmd Issues

### ISSUE THREAD

**Issue by bmillerbma** [Azure/azure-iot-remote-monitoring#55]
Some issues with the build command script::

* The "clean" (i.e., rmdir) operation can fail and requires closing Visual Studio (the vshost.exe file is in use)
* The msbuild command does not work wit VisualStudio 2015
* msbuild must be in your path to execute the script
* The cmd script is sparsely documented and cannot be debugged

The following powershell script can be used to replace the build shell script:

https://github.com/bmillerbma/azure-iot-remote-monitoring/commit/67bacf8d4c1cbe86090c56e1c9ac4ee9095ccd23

**Comment by jamesweb-ms** [comment]
* Clean should probably be removed, as should the redirect to build output.  This was legacy from WorkerRoles.
* Not sure what you mean by msbuild doesn't work with VS2015?  You can find the VSDevCmd.bat in the same place: Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools
* If you run previous, msbuild is in your path.

I'm open to adding a powershell script (which is pretty much what already drives deployment), there was just more demand for CMD driven deployment in our private preview, which is why it was wrapped that way.  I think having both is good.

**Comment by bmillerbma** [comment]
I promise not to push any harder after this ;)  This PS vs CMD issue is somewhat subjective, but there are some real issues with the CMD script -- the issues I raised here and the confusion illustrated in issue https://github.com/Azure/azure-iot-remote-monitoring/issues/4  My colleagues trying to deploy this were also flummoxed by the CMD script wrapper.  Some notes:

* The powershell scripts are easier to parameterize and document -- they are self-documenting, in fact.  
* re: Clean -- OK, but in the meantime, the powershell script solves the problem.  And provides a more robust launching point.
* re: VS2015 -- the /P:VisualStudioVersion=12.0 switch results in a "error MSB4019" error.  The powershell script also hard-codes this, but, again, it's a starting point for something more robust.  There are other powershell build functions that can be substituted.  With the CMD script, you're limited.
* re: path.  I must run this every time, right?  Would this become part of the script?
* re: having both.  I would personally prefer just one point of entry and one script to maintain.

**Comment by jamesweb-ms** [comment]
The more I think about this, the more I think we should go the route of a VS Extension.  The problem with powershell as it has no context regarding VS (your script also can get MSbuild.exe wrong since its referencing the .Net version).  VSStudioCmd prompt at least knows what version it is (The MSBuild param should actually reference %VISUALSTUDIOVERSION%).

If we go the Extension route, then everything can be done via Visual Studio without dropping to a shell.  If you are interested in investigating this approach, let me know.  Otherwise I will look at putting something like that on the backlog.

**Comment by bmillerbma** [comment]
I'll pass on the extension extension ;)  FYI: Folks at work like this module, which degrades gracefully through VS versions.  

https://invokemsbuild.codeplex.com/

I believe I'll add this to my fork and keep moving from here.  Thanks for your efforts.  Once I found the October Integration branch, things moved much more smoothly.

**Comment by jamesweb-ms** [comment]
I removed the explicit reference to VisualStudioVersion=12.0, so now it builds for both VS2013 and VS2015.  I also opened a new issue to track the PS vs CMD request.  Feel free to add your comments there.  We won't be taking that change for October-Integration, as we are getting ready to merge now.  But after we get some feedback, we can take the decision for the November update.
